### ISSUE TITLE
Few things that I could not understand you did during transformation of template to gatsby project.

### ISSUE THREAD

**Issue by sabbiu** [anubhavsrivastava/gatsby-starter-solidstate#1]
I am new to gatsby and wanted to translate html template to gatsby project. In searching so, I found out that you have done the same. I could not understand few things. It would be really helpful if you could explain me what is going on here.

1. Here, https://github.com/anubhavsrivastava/gatsby-starter-solidstate/blob/master/src/assets/sass/layout/_menu.scss#L62, the relative path doesn't trace back to images folder. How does this reference work?

2. There are many js files provided with the template.
![image](https://user-images.githubusercontent.com/19733021/60859407-44550d80-a232-11e9-9011-b17fe0110e00.png)
I can see the logic from main.js implemented in the form of react in respective component. What about other js files? Shouldn't they be imported too.

For now, I only have these questions. I might bug you if I get any problems further during development. Thanks.

**Comment by anubhavsrivastava** [comment]
I guess I am quite late to address this,
1. The relative path resolves to [/src/assets/images/close.svg](https://github.com/anubhavsrivastava/gatsby-starter-solidstate/blob/master/src/assets/images/close.svg)
2. Other files are jQuery dependencies and other library that are required to achieve whatever is done in main.js or util.js (which has been moved to React Component logic, as you pointed). This files are not needed anymore hence they are not part of the starter
